#import "../styles/article.typ": *

#show: article.with(
title: "On the Convergence of Iterative Methods",
author: "John Doe",
affiliation: "Department of Mathematics, University of Example",
email: "john.doe@example.edu",
date: "January 2024",
abstract: "We investigate the convergence properties of various iterative methods for solving linear systems. Our main result establishes a new sufficient condition for convergence that generalizes previous work in this area.",
keywords: "iterative methods, convergence, linear systems, numerical analysis",
)

= Introduction
Iterative methods play a crucial role in solving large-scale linear systems that arise in scientific computing and engineering applications.
  
#definition(title: "Iterative Method", id: "iterative-method")[
An iterative method for solving $A x = b$ is a sequence of approximations ${x_k}$ generated by the recurrence relation
$x_{k+1} = B x_k + c$
where $B$ is the iteration matrix and $c$ is a constant vector.
]
  
#theorem(title: "Convergence Criterion", id: "convergence-criterion")[
The iterative method converges if and only if the spectral radius of the iteration matrix satisfies $rho(B) < 1$.
]
  
#proof(id: "main-proof")[
Let $e_k = x_k - x^*$ be the error at iteration $k$, where $x^*$ is the exact solution.
Then $e_{k+1} = B e_k$, which implies $e_k = B^k e_0$.
The method converges if and only if $lim_(k-> oo ) B^k = 0$,
which is equivalent to $rho(B) < 1$.
]
    
= Analysis of Specific Methods
== Jacobi Method
The Jacobi method uses the iteration matrix $B = D^(-1)(L + U)$ where $A = D - L - U$.
    
#proposition(title: "Jacobi Convergence", id: "jacobi-convergence")[
If $A$ is strictly diagonally dominant, then the Jacobi method converges.
]
  
#proof(id: "jacobi-proof")[
For strictly diagonally dominant matrices, we have $|a_(i i)| > sum_(j!=i) |a_(i j)|$ for all $i$.
This implies $rho(B) < 1$ by the Gerschgorin circle theorem.
]

== Gauss-Seidel Method
The Gauss-Seidel method typically converges faster than Jacobi for the same matrix.
  
#lemma(title: "Comparison Lemma", id: "comparison-lemma")[
For any matrix $A$, the spectral radius of the Gauss-Seidel iteration matrix is less than or equal to that of the Jacobi iteration matrix.
]
  
#corollary(title: "Gauss-Seidel Convergence", id: "gauss-seidel-convergence")[
If the Jacobi method converges, then the Gauss-Seidel method also converges.
]
  
= Numerical Examples
== Simple 2x2 System
Consider the system
  $((2, 1), (1, 3)) ((x_1), (x_2)) = ((5), (6))$
This matrix is strictly diagonally dominant, so both Jacobi and Gauss-Seidel methods converge.

#remark(title: "Implementation Note", id: "implementation-note")[
In practice, one should check the condition number of the matrix as well as the spectral radius to predict convergence behavior.
]